### ISSUE TITLE
Cant start scandir@ service

### ISSUE THREAD

**Issue by ajhfsdh** [mobinmob/void-66-services#156]
Whenever i try to enable the scandir@<username> service, for user services, it seems to fail at the setenv@ service with the following error:
`execl-toc: fatal: unable to create dir: @PATH_ENVIRONMENT@: Permission denied`
`s6-rc: warning: unable to start service setenv@<username>: command exited 111`
`66-start: fatal: unable to start services selection`
I am pretty sure this is an error on my part, but I have used Obarun in the past and never saw this issue, so I am unsure how to solve it.
I have tried deleting all trees, and rebuilding them, and tried 66-update, but nothing seems to solve this issue.

**Comment by ajhfsdh** [comment]
```~ > doas 66-tree -nE user
doas (<username>@<hostname>) password:
66-tree: info: Created successfully tree: user
66-tree: info: Enabled successfully tree: user
~ > doas 66-enable -t user scandir@<username>
66-enable: info: Enabled successfully: setenv@<username>
66-enable: info: Enabled successfully: svscan@<username>
66-enable: info: Enabled successfully: scandir@<username>
~ > doas 66-start -t user scandir@<username>
66-start: info: Initialized successfully: setenv@<username>  
66-start: info: Initialized successfully: svscan@<username>-log  
66-start: info: Initialized successfully: svscan@<username>
66-start: info: Initialized successfully: scandir@<username>
execl-toc: fatal: unable to create dir: @PATH_ENVIRONMENT@: Permission denied  
s6-rc: warning: unable to start service setenv@<username>: command exited 111  
66-start: fatal: unable to start services selection  ```

**Comment by mobinmob** [comment]
Thank you for the output.
Have you installed the scandir-66serv package from my repo?
If you followed the [documentation](https://github.com/mobinmob/void-66-services/blob/master/conf/void-66-conf.md) to create your trees and enable basic services, you will have 3 trees: boot, default and runit. This is the setup I **run and recommend**. I choose the specific setup because it is simple, clean and tries to follow the voidlinux policy, having a single "runlevel" named default for the services. If you have that setup, you can enable and run the scandir@ service for you username in the `current` tree, the `default` tree.

**Comment by ajhfsdh** [comment]
I had installed everything like the documentation suggested. I ended up trying to reinstall Void with the install rather than through chroot, and this fixed the issue. I most likely messed something up in the chroot install, just not sure what.

**Comment by mobinmob** [comment]
> I had installed everything like the documentation suggested. I ended up trying to reinstall Void with the install rather than through chroot, and this fixed the issue. I most likely messed something up in the chroot install, just not sure what.

Thank you for reporting back with a success :)
Ι will have a much more streamlined process for user services soon - I hope... See here for some [information](https://github.com/mobinmob/void-66-services/issues/155#issuecomment-1002627255).
