### ISSUE TITLE
dcron service: "setpgid: Operation not permitted"

### ISSUE THREAD

**Issue by flexibeast** [mobinmob/void-66-services#54]
Since upgrading to s6 2.10.0.0, the dcron service has stopped working; the log file is simply a stream of messages:

    setpgid: Operation not permitted

which seems to be [the issue mentioned in the dcron service file](https://github.com/dubiousjim/dcron/issues/13), presumably reintroduced by the s6 change:

> The nosetsid file is not recognized anymore in service directories. s6-supervise now always starts it child as a session leader.

Can anything be done about this at the service level, or is it something that can only be addressed in dcron itself? If the latter, and given that dcron issue 13 is apparently not going to be addressed any time soon, maybe the dcron service should simply be removed?

**Comment by mobinmob** [comment]
Yes, since v. 2.10.0.0 s6 does not support nosetsid. I do not thing it can be solved at te service level/script. @CasperVector has a patch for dcron : https://github.com/CasperVector/slew/tree/master/pkg/dcron/misc
Ι will probably remove the service - I want to try something first. I will probably tag a release today or tommorow, I will resolve this one way or the other before that.
Thanks for the report :)

**Comment by mobinmob** [comment]
Closing, fix included in version 0.0.2.
